<template>
  <div>
      <el-table
    :data="list"
    border
    style="width: 100%">
    <el-table-column
      fixed
      prop="memberPhone"
      label="电话号码"
      width="150">
    </el-table-column>
    <el-table-column
      prop="memberAcount"
      label="昵称"
      width="120">
    </el-table-column>
    <el-table-column
      prop="memberCard"
      label="会员卡号"
      width="150">
    </el-table-column>
    <el-table-column
      prop="memberPoint"
      label="积分"
      width="80">
    </el-table-column>
    <el-table-column
      prop="memberName"
      label="真实姓名"
      width="120">
    </el-table-column>
    <el-table-column
      prop="memberAdd"
      label="送货地址">
    </el-table-column>
    <el-table-column
      fixed="right"
      label="操作"
      width="100">
      <template slot-scope="scope">
        <el-button
        type="text"
         @click="updata(scope.row)"
        size="small">修改</el-button>
        <el-button
        type="text"
        @click="del(scope.row)"
        size="small">删除</el-button>
      </template>
    </el-table-column>
  </el-table>
  <div class="block" style="width:800px;margin:auto">
    <el-pagination
      @size-change="handleSizeChange"
      @current-change="handleCurrentChange"
      :current-page="curpage"
      :page-sizes="[10,20,30,40]"
      :page-size="rows"
      layout="total, sizes, prev, pager, next, jumper"
      :total="total">
    </el-pagination>
  </div>
  </div>
</template>
<script>
import {mapState,mapMutations,mapGetters,mapActions} from "vuex"
export default {
  name:"memberList",
  watch:{
    rows:function(){
      this.getCember()
    },
    page:function(){
      this.getCember()
    }
  },
  computed:{
    ...mapState("MemberStore",["list","page","rows","curpage","eachpage","total","maxpage"]),
  },
  methods:{
    ...mapMutations("MemberStore",["del","updata","handleSizeChange","handleCurrentChange"]),
    ...mapActions("MemberStore",["getCember"])
  },
 created(){
   this.getCember()
 }
}
</script>